version: "3.9"
services:
  bungee:
    container_name: Bungee
    image: ghcr.io/theflyingbirdsmc/pluget:latest
    depends_on:
      - mysql
    ports:
      - 25565:25565
      - 8804:8804
    environment:
      - COMPOSE_PROJECT_NAME=Bungee
      - GITHUB_REPOSITORY=https://github.com/theflyingbirdsmc/TFB-Bungee.git
      - GITHUB_EMAIL=fuglenbusiness@gmail.com
      - GITHUB_USERNAME=Fuglen
      - BUILD_NUMBER=latest
      - MINECRAFT_VERSION=latest
      - SERVER_JARFILE=server.jar
    volumes:
      - "bungee:/home/container"
  lobby:
    container_name: Lobby
    image: ghcr.io/theflyingbirdsmc/pluget:latest
    depends_on:
      - bungee
      - mysql
    ports:
      - 25600:25600
    environment:
      - GITHUB_REPOSITORY=https://github.com/theflyingbirdsmc/TFB-Lobby.git
      - GITHUB_EMAIL=fuglenbusiness@gmail.com
      - GITHUB_USERNAME=Fuglen
      - BUILD_NUMBER=latest
      - MINECRAFT_VERSION=1.18.2
      - SERVER_JARFILE=server.jar
    volumes:
      - "lobby:/home/container"
  mysql:
    image: mysql:latest
    restart: always
    expose:
      - 3306
    environment:
      - MYSQL_DATABASE=s1_luckperms
      - MYSQL_USER=tfbdev
      - MYSQL_PASSWORD=tfb123
volumes:
  bungee:
  lobby:
  mysql:
