version: "3.9"
services:
  tfb:
    container_name: TFB
    build: ./
    depends_on:
      - database
    ports:
      - 25565:25565
      - 8804:8804
      - 8192:8192
    environment:
      - GITHUB_EMAIL=${GITHUB_EMAIL}
      - GITHUB_USERNAME=${GITHUB_USERNAME}
    volumes:
      - "../:/home/container/TFB"
    networks:
      tfb:
        ipv4_address: 172.17.0.3
  database:
    container_name: Database
    image: mariadb:10.7
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - "database:/var/lib/mysql"
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    networks:
      tfb:
        ipv4_address: 172.17.0.2
volumes:
  tfb:
  database:
networks:
  tfb:
    driver: bridge
