version: "3.9"
services:
  bungee:
    container_name: Bungee
    image: ghcr.io/theflyingbirdsmc/pluget:latest
    depends_on:
      - database
    ports:
      - 25565:25565
      - 8804:8804
      - 25600:25600
      - 25601:25601
      - 25700:25700
    environment:
      - COMPOSE_PROJECT_NAME=Bungee
      - GITHUB_REPOSITORY=https://github.com/theflyingbirdsmc/TFB-Bungee.git
      - GITHUB_EMAIL=${GITHUB_EMAIL}
      - GITHUB_USERNAME=${GITHUB_USERNAME}
    volumes:
      - "tfb:/home/container"
  database:
    container_name: Database
    image: mariadb:10.7
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - "database:/var/lib/mysql"
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
volumes:
  tfb:
  database:
