version: "3.9"
services:
  bungee:
    container_name: Bungee
    image: ghcr.io/theflyingbirdsmc/pluget:latest
    depends_on:
      - database
    ports:
      - 25565:25565
      - 8804:8804
    environment:
      - COMPOSE_PROJECT_NAME=Bungee
      - GITHUB_REPOSITORY=https://github.com/theflyingbirdsmc/TFB-Bungee.git
      - GITHUB_EMAIL=fuglenbusiness@gmail.com
      - GITHUB_USERNAME=Fuglen
    tty: true
    volumes:
      - "bungee:/home/container"
    networks:
      - tfb
  lobby:
    container_name: Lobby
    image: ghcr.io/theflyingbirdsmc/pluget:latest
    depends_on:
      - bungee
      - database
    ports:
      - 25600:25600
    environment:
      - COMPOSE_PROJECT_NAME=Lobby
      - GITHUB_REPOSITORY=https://github.com/theflyingbirdsmc/TFB-Lobby.git
      - GITHUB_EMAIL=fuglenbusiness@gmail.com
      - GITHUB_USERNAME=Fuglen
    tty: true
    volumes:
      - "lobby:/home/container"
    networks:
      - tfb
  creative:
    container_name: Creative
    image: ghcr.io/theflyingbirdsmc/pluget:latest
    depends_on:
      - bungee
      - database
      - lobby
    ports:
      - 25601:25601
    environment:
      - COMPOSE_PROJECT_NAME=Creative
      - GITHUB_REPOSITORY=https://github.com/theflyingbirdsmc/TFB-Creative.git
      - GITHUB_EMAIL=fuglenbusiness@gmail.com
      - GITHUB_USERNAME=Fuglen
    tty: true
    volumes:
      - "creative:/home/container"
    networks:
      - tfb
  database:
    container_name: Database
    image: mariadb:10.7
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
    tty: true
    volumes:
      - "database:/var/lib/mysql"
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    networks:
      tfb:
        ipv4_address: 172.17.0.1
volumes:
  bungee:
  lobby:
  creative:
  database:
networks:
  tfb:
    driver: bridge
    ipam:
      config:
        - subnet: 172.17.0.0/16
          gateway: 172.17.0.10
