apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Creative
  description: Build your dreams!
  # labels:
  #   example.com/custom: custom_label_value
  # annotations:
  #   example.com/service-discovery: artistweb
  #   circleci.com/project-slug: github/example-org/artist-website
  tags:
    - paper
    - "1.19.4"
    - creative
  links:
    - url: https://panel.theflyingbirds.net/server/ebdfb423
      title: Admin Dashboard
      icon: dashboard
      type: admin-dashboard
spec:
  type: server
  lifecycle: production
  owner: theflyingbirdsmc/eu
  # system: eu
  # domain: tfb-network