enforce_secure_profile: false
listeners:
- bind_local_address: true
  force_default_server: true
  forced_hosts:
    pvp.md-5.net: pvp
  host: 0.0.0.0:25565
  max_players: 2023
  motd: ''
  ping_passthrough: false
  priorities:
  - lobby
  proxy_protocol: false
  query_enabled: false
  query_port: 25565
  tab_list: GLOBAL_PING
  tab_size: 60
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  default:
  - bungeecord.command.server
  - bungeecord.command.list
log_pings: true
connection_throttle_limit: 3
server_connect_timeout: 5000
timeout: 20000
player_limit: 2021
prevent_proxy_connections: false
ip_forward: true
groups:
  md_5:
  - admin
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
stats: eeff8c06-80b0-49a1-ab8c-697022039a24
online_mode: true
forge_support: false
disabled_commands:
- revertaddresses
servers:
  lobby:
    address: theflyingbirds.net:32001
    motd: ''
    restricted: false
  creative:
    address: theflyingbirds.net:32002
    motd: ''
    restricted: false
  factions:
    address: theflyingbirds.net:32003
    motd: ''
    restricted: false
  parkour:
    address: theflyingbirds.net:32004
    motd: ''
    restricted: false
  vanilladk:
    address: theflyingbirds.net:32005
    motd: ''
    restricted: false
  vanilla_old:
    address: theflyingbirds.net:32006
    motd: ''
    restricted: false
