version: "3.7"
services:
  bungee:
    build: TFB-Bungee
    #target: development
    expose:
      - 25565
      - 8804
  mysql:
    image: mysql:latest
    restart: always
    expose: 
      - 3306
    #command: --init-file /docker-entrypoint-initdb.d/init.sql
    volumes:
        - ./setup.sql:/docker-entrypoint-initdb.d"
    environment:
        MYSQL_USER: tfbdev
        MYSQL_PASSWORD: tfb123