name: Docker Build

on:
  push:
    branches:
      - dev
    paths: 
      - 'TFB_Vanilla/**'
      - 'TFB-Creative/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ["TFB_Vanilla", "TFB-Creative"]

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      if: contains(github.event.head_commit.modified, matrix.project)
      uses: docker/build-push-action@v2
      with:
        context: ./${{ matrix.project }}
        push: true
        tags: your-dockerhub-username/${{ matrix.project }}:latest
