name: Docker Build

on:
  push:
    branches:
      - dev
    paths: 
      - 'TFB_Vanilla/**'
      - 'TFB-Creative/**'
      - '.github/workflows/build.yml'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ["tfb-vanilla", "tfb-creative"]

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Setup Java and Gradle
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Execute Gradle build
      env:
        MAVEN_URL: ${{ secrets.MAVEN_URL }}
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
      run: |
        cd ${{ matrix.project }} && gradle server && gradle plugins    

    - name: Login to Artifactory
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.ARTIFACTORY_URL }}
        username: ${{ secrets.ARTIFACTORY_USERNAME }}
        password: ${{ secrets.ARTIFACTORY_PASSWORD }}

    - name: Build and push
      if: contains(github.event.head_commit.modified, matrix.project)
      uses: docker/build-push-action@v2
      with:
        context: ./${{ matrix.project }}
        push: true
        tags: ${{ secrets.ARTIFACTORY_DOCKER_REPO }}/${{ matrix.project }}:latest
