# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "live" branch
  push:
    branches: ["live"]
  pull_request:
    branches: ["live"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "transform"
  transform:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: live
      - name: Run read-yaml action
        id: live_values
        uses: jbutcher5/read-yaml@main # You may wish to replace main with a version tag such as '1.6' etc.
        with:
          file: "./.github/workflows/scripts/live_values.yml" # File to read from
          key-path: '["TFB-Flamecord/config.yml"]' # Access the runs key then the using key and retuns the value.
      - name: Display read-yaml output
        run: echo "${{ steps.live_values.outputs.data }}"

      - name: Read values in file on live
        id: read-file
        uses: jbutcher5/read-yaml@main # You may wish to replace main with a version tag such as '1.6' etc.
        with:
          file: "./TFB-Flamecord/config.yml" # File to read from
          key-path: "${{ steps.live_values.outputs.data }}" # Access the runs key then the using key and retuns the value.
      - name: Display read-file output
        run: echo "${{ steps.read-file.outputs.data }}"

      - uses: actions/checkout@v3

      - uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: "TFB-Flamecord/config.yml"
          description: Test GitHub Action
          message: "Update file"
          title: "Version Updates"
          branch: dev
          changes: |
            {
              "TFB-Flamecord/config.yml": {"servers":${{ steps.read-file.outputs.data}}}
            }
