name: Build and Publish Parkour Docker Image to Nexus Artifactory

on:
  push:
    paths:
      - 'TFB-Parkour/**'

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      # Login to Nexus Artifactory
      - name: Login to Nexus Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.MAVEN_DOCKER_REPO }} # change this to your Nexus Registry URL
          username: ${{ secrets.MAVEN_USERNAME }}
          password: ${{ secrets.MAVEN_PASSWORD }}

      # Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./TFB-Parkour # specifying the directory where your Dockerfile is
          file: ./TFB-Parkour/Dockerfile # specifying the path to your Dockerfile
          push: true
          tags: ${{ secrets.MAVEN_DOCKER_REPO }}/parkour:latest # change this to your image name