name: Dynamic Production Workflow

on:
  push:
    branches:
      - main

jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Get changed folder
        id: get_changed_folder
        run: echo ::set-output name=folder::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -o '^[^/]*' | uniq)

      - name: Execute Gradle build
        env:
          MAVEN_URL: ${{ secrets.MAVEN_URL }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        run: |
          if [[ ${{ steps.get_changed_folder.outputs.folder }} != ".devcontainer" ]]; then
            cd ${{ steps.get_changed_folder.outputs.folder }}
            gradle update --no-build-cache
          else
            echo "Skipping .devcontainer folder"
          fi

      - name: Login to Nexus Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REPO }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./${{ steps.get_changed_folder.outputs.folder }}
          file: ./${{ steps.get_changed_folder.outputs.folder }}/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_REPO }}/${{ steps.get_changed_folder.outputs.folder }}:latest
          build-args: |
            STREAMINGDROPS_DISCORD_WEBHOOK=${{ secrets.STREAMINGDROPS_DISCORD_WEBHOOK }}
