name: Build and Publish Docker Images to Nexus Artifactory

on:
  push:
    paths:
      - 'TFB-Creative/**'
      - 'TFB-Factions/**'
      - 'TFB-Flamecord/**'
      - 'TFB-Lobby/**'
      - 'TFB-Parkour/**'
      - 'TFB-Vanilla/**'
      - '.github/servers.yml'
    branches:
      - live
      - kubernetes

jobs:
  build-test:
    name: Build and Test ${{ matrix.service }} Docker Image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [creative, factions, flamecord, lobby, parkour, vanilla]
        include:
          - service: Creative
            directory: TFB-Creative
          - service: Factions
            directory: TFB-Factions
          - service: Flamecord
            directory: TFB-Flamecord
          - service: Lobby
            directory: TFB-Lobby
          - service: Parkour
            directory: TFB-Parkour
          - service: Vanilla
            directory: TFB-Vanilla
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        env:
          MAVEN_URL: ${{ secrets.MAVEN_URL }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        run: |
          cd ${{ matrix.directory }}
          gradle server
          gradle plugins

  publish:
    name: Publish ${{ matrix.service }} Docker Image
    needs: build-test
    if: github.ref == 'refs/heads/kubernetes'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [creative, factions, flamecord, lobby, parkour, vanilla]
        include:
          - service: Creative
            directory: TFB-Creative
          - service: Factions
            directory: TFB-Factions
          - service: Flamecord
            directory: TFB-Flamecord
          - service: Lobby
            directory: TFB-Lobby
          - service: Parkour
            directory: TFB-Parkour
          - service: Vanilla
            directory: TFB-Vanilla
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Nexus Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.MAVEN_DOCKER_REPO }}
          username: ${{ secrets.MAVEN_USERNAME }}
          password: ${{ secrets.MAVEN_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./${{ matrix.directory }}
          file: ./${{ matrix.directory }}/Dockerfile
          push: true
          tags: ${{ secrets.MAVEN_DOCKER_REPO }}/${{ matrix.service }}-kubernetes:latest