name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_call:
    secrets:
      MAVEN_URL:
        required: true
      MAVEN_USERNAME:
        required: true
      MAVEN_PASSWORD:
        required: true
      DOCKER_PASSWORD:
        required: true
      DOCKER_USERNAME:
        required: true
      DOCKER_REGISTRY:
        required: true
      DOCKER_REPO:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository containing the shared Dockerfile
      - name: Checkout shared Dockerfile repository
        uses: actions/checkout@v3
        with:
          repository: theflyingbirdsmc/TFB-Network
          path: ${{ github.workspace }}/TFB-Network

      # Check out the Minecraft server repository
      - name: Checkout Minecraft server repository
        uses: actions/checkout@v3
        with:
          path: ${{ github.workspace }}

      # Set up Docker
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        env:
          MAVEN_URL: ${{ secrets.MAVEN_URL }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        run: gradle update --no-build-cache

      # Login to Nexus Artifactory
      - name: Login to Nexus Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: List files for debugging
        run: |
          echo "Contents of workspace:"
          ls -R ${{ github.workspace }}
          echo "Contents of TFB-Network:"
          ls -R ${{ github.workspace }}/TFB-Network

      # Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ${{ github.workspace }} # context of the Minecraft server repository
          file: ${{ github.workspace }}/TFB-Network/.github/docker/Dockerfile # path to the shared Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_REPO }}/parkour:latest